[package]
name = "pufferfish-parser"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
fancy-regex = "0.8.0" # Has backreferencing, etc.
lazy_static = "1.4.0"
concat_strs = "1.0.2"