[package]
name = "pufferfish"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.14"
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
regex = "1.5.4"
serde_json = "1.0.79"
minify-html = "0.8.0"
minify-html-onepass = "0.8.0"
